server:
  port: 8080
#  servlet:
#    context-path: /pre
spring:
  application:
    name: mybatis-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/world?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.182.138:8848
        username: nacos
        password: nacos
        namespace: public
        enabled: false

mybatis-plus:
  mapper-locations: classpath:mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    log-impl: com.example.mybatisdemo.config.SqlOutLogConfig

# 异步线程配置
# 配置核心线程数
async:
  executor:
    thread:
      # 配置核心线程数
      corePoolSize: 10
      # 配置最大线程数
      maxPoolSize: 30
      # 配置队列大小
      queueCapacity: 99988
      # 配置线程池中的线程的名称前缀
      namePrefix: async-thread-
